-- AlterTable
ALTER TABLE "User" ADD COLUMN "startLabel" TEXT,
ADD COLUMN "startLat" DOUBLE PRECISION,
ADD COLUMN "startLng" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Settings" ADD COLUMN "fuelType" TEXT NOT NULL DEFAULT 'Gasolio',
ADD COLUMN "consumoL100" DOUBLE PRECISION NOT NULL DEFAULT 7,
ADD COLUMN "fuelPrice" DOUBLE PRECISION,
ADD COLUMN "fuelPriceAt" TIMESTAMP(3);
